---
title: "Case study_Predictiton"
output: html_notebook
---

```{r}
library(dummies)
library(ggplot2)
library(car)
library(kader)
library(MASS)
library(scales)
library(psych)
library(e1071)
library(outliers)
library(rpart)
library(rpart.plot)
library(randomForest)
library(caret)
library(mgcv)
library(ROCR)
library(gains)
library(Metrics)
library(caTools)
library(e1071)
library(gmodels)
library(corrplot)
```


```{r Import cleaned data}
Music_=read.csv("spotifyclean.csv",
                stringsAsFactors=FALSE,na.strings = "")

Music=Music_[,-c(1,3,5,14)]

```


```{r}
#SAMPLING 50-30-20

set.seed(111)
#SAMPLING 50-30-20
set.seed(111)

train.index2 <- sample(row.names(Music), 0.5*dim(Music)[1])
valid_Test.index <- setdiff(row.names(Music), train.index2)

MusicTrain <- Music[train.index2,]
valid_Test.df <- Music[valid_Test.index,]


valid.index2 <- sample(row.names(valid_Test.df),
                        0.6*dim(valid_Test.df)[1])
test.index2 <- setdiff(row.names(valid_Test.df),
                        valid.index2)

MusicValid <- valid_Test.df[valid.index2,]
MusicTest <- valid_Test.df[test.index2,]


```




```{r Random forest }
rf <- randomForest(popularity~., data = MusicTrain)
rf
importance(rf)
rf.pred.train <- predict(rf, MusicTrain)
rf.pred.valid <- predict(rf, MusicValid)
rf.prerd.test <- predict(rf, MusicTest)

#use rmse to evaluate the performance
rmse.train <- RMSE(rf.pred.train, MusicTrain$popularity)#3.346
rmse.valid <- RMSE(rf.pred.valid, MusicValid$popularity)#7.747
rmse.test <- RMSE(rf.prerd.test, MusicTest$popularity)#7.888

gain <- gains(MusicValid$popularity,
              rf.pred.valid, groups = 100)
{plot(c(0, gain$cume.pct.of.total*sum(MusicValid$popularity))~c(0, gain$cume.obs))
lines(c(0, sum(MusicValid))~c(0, dim(MusicValid)[1]))}

#The RMSE shows that this model is good.

```



```{r SVM}
mu.svm <- svm(Music[,-1], Music[,1])
data.frame(actual=Music[,1], predicted=mu.svm$fitted)
rmse.svm <- RMSE(mu.svm$fitted, Music$popularity)#7.52

gain <- gains(Music$popularity,
              mu.svm$fitted, groups = 100)
{plot(c(0, gain$cume.pct.of.total*sum(Music$popularity))~c(0, gain$cume.obs))
lines(c(0, sum(Music))~c(0, dim(Music)[1]))}

#this model is good

```



```{r LDA}
Music2=Music_[,-c(1,3,5,2)]


set.seed(111)
train.indexm <- sample(row.names(Music2), 0.6*dim(Music)[1])
valid_Test.indexm <- setdiff(row.names(Music2), train.indexm)

MusicTrain.cl <- Music2[train.indexm,]
MusicValid.cl <- Music2[valid_Test.indexm,]


mu.lda <- lda(popularcategory~., MusicTrain.cl)

mu.lda.pred <- predict(mu.lda, as.data.frame(MusicValid.cl[,-11]))

data.frame(actual=MusicValid.cl[,10], predicted=mu.lda.pred$class)

confusionMatrix(as.factor(MusicValid.cl$popularcategory), as.factor(mu.lda.pred$class))


```


